require 'spec_helper'

feature "Site Navigation" do


  scenario "Viewing and Editing Profile" do
    visit 'users'
    click_link 'Sign Up'
    fill_in 'Name', :with => 'Emma'
    fill_in 'Email', :with => 'm@m.com'
    fill_in 'Username', :with => 'emmadilemma'
    fill_in 'Password', :with => '1234'
    fill_in 'Password confirmation', :with => '1234'
    fill_in 'Location', :with => 'Charlotte, NC'
    fill_in 'Role in wedding', :with => 'Bride'
    fill_in 'Total budget amount', :with => '1000'
    click_button 'Create User'
    page.should have_content 'Profile created. Welcome!'
    visit root_path
    click_on 'Log Out'
    page.should have_content 'Logged out!'
    click_on 'Log In'
    fill_in 'Email', :with => 'm@m.com'
    fill_in 'Password', :with => '1234'
    page.should have_content 'Home'
    click_button 'Log In'
    page.should have_content 'Logged in as emmadilemma.'
    click_on 'View Profile'
    page.should have_content 'Emma is the Bride!'
    click_on 'Edit Profile'
    page.should have_content 'Edit Profile'
    page.should have_content 'View Profile'
    page.should have_content 'Home'
    page.should have_content 'Log Out'
    page.should have_content 'Logged in as emmadilemma.'
    fill_in 'Name', :with => 'Em'
    fill_in 'Email', :with => 'emma@ma.com'
    fill_in 'Username', :with => 'EmmaD'
    fill_in 'Password', :with => '123456'
    fill_in 'Password confirmation', :with => '123456'
    fill_in 'Location', :with => 'Portland, OR'
    fill_in 'Role in wedding', :with => 'Bride'
    fill_in 'Total budget amount', :with => '10000'
    click_on 'Update User'
    page.should have_content 'Thank you for updating your profile!'
    click_on 'Log Out'
    click_on 'Log In'
    fill_in 'Email', :with => 'emma@ma.com'
    fill_in 'Password', :with => '123456'
    click_button 'Log In'
    page.should have_content 'Logged in as EmmaD'
  end
end
